### ISSUE TITLE
Error with scaped pipes

### ISSUE THREAD

**Issue by equiman** [yoshi389111/vscode-md-table-rainbow#1]
First of all, thank you for creating this useful extension. I love it ♥

I would like to report this scenario: scaped pipes `\|` have been treated as an additional column.

Example
```markdown
| Alias  | Command                                     |
| ------ | ------------------------------------------- |
| `sp`   | `swpm --pin <npm\|yarn[@berry]\|pnpm\|bun>` |
| `spn`  | `swpm --pin npm`                            |
| `spy`  | `swpm --pin yarn`                           |
| `spp`  | `swpm --pin pnp`                            |
| `spb`  | `swpm --pin bun`                            |
```

![image](https://user-images.githubusercontent.com/933393/234980607-a2cd5767-034d-4f47-9acb-0c8221b61842.png)

![image](https://user-images.githubusercontent.com/933393/234980697-9ea6ad35-59e3-49e1-b773-8b6ca6d6669d.png)

![image](https://user-images.githubusercontent.com/933393/234980763-297996b9-7ba3-4f84-a44f-ba26366bd1fb.png)

**Comment by yoshi389111** [comment]
Hello, equiman.

Thank you for your bug report.

Fix to handle escaped pipes correctly.
Try version 1.0.1.

**Comment by equiman** [comment]
Perfect, now it works well!

![image](https://user-images.githubusercontent.com/933393/235221517-9fd20451-0372-4240-b677-e94bad92d3db.png)

Thanks for the quick fix.
